sonar.organization=thinha1
sonar.projectKey=Thinha1_fashion-store
sonar.projectName=fashion-store
sonar.sourceEncoding=UTF-8

sonar.sources=app,config,database,resources,routes,.github,.docker,compose.yaml
sonar.tests=tests

sonar.exclusions=resources/views/vendor/**,public/build/**
sonar.coverage.exclusions=config/**,database/**,resources/**,routes/**

sonar.php.coverage.reportPaths=build/coverage/clover.xml
sonar.php.tests.reportPath=build/test-results/phpunit.xml

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
